#!/usr/bin/env node -r ./babel-register

import { join as joinPath } from "path";
import { readFileSync, writeFileSync } from "fs";

const targetFile = joinPath(__dirname, "..", "src", "generated-fixtures.ts");

const fixtures = [];
for (const [name, path] of [
  ["Ars Technica", "2md/fixtures/quote1.html"],
  ["MDN", "2md/fixtures/quote2.html"],
  ["Node JS", "2md/fixtures/nodejs.html"],
  ["Stack Overflow", "2md/fixtures/quote3.html"]
]) {
  fixtures.push([name, readFileSync(require.resolve(path)).toString()]);
}

const output = `\
// auto-generated by gen-fixtures.ts

export const fixtures = new Map(${JSON.stringify(fixtures, null, 2)});`;

writeFileSync(targetFile, output);
console.log(`wrote ${targetFile}`);
