#!/bin/bash

set -eu

DIR="$(dirname -- "${0}")"

cd "${DIR}"

require_password=true
if [ "${1}" = "--no-password" ]; then
    require_password=false
    shift
fi

TARGET="${1}"
USER="${TARGET%@*}"
DOMAIN="${TARGET#*@}"

node -r ./babel-register.js src/gen-fixtures.tsx

rm -rf dist && \
    yarn parcel build \
        src/demo.html \
        src/email.html \
        src/index.html \
        src/how-it-works.html

mv dist/demo{.html,}
mv dist/email{.html,}
mv dist/how-it-works{.html,}

if $require_password; then
    PASSWORD_CONFIG="
<Else>
AuthType Basic
AuthName \"Authorization required\"
AuthUserFile /home/${USER}/${DOMAIN}/.htpasswd
Require user andrew
</Else>"
else
    PASSWORD_CONFIG=""
fi

cat <<EOF > dist/.htaccess
<If "%{HTTPS} != 'on'">
RewriteEngine On
RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
</If>
${PASSWORD_CONFIG}

Header set Content-Security-Policy "default-src 'self'; style-src 'self' 'unsafe-inline'; img-src *;"
Header set Strict-Transport-Security max-age=2592000

AddDefaultCharset UTF-8

ErrorDocument 401 default
ErrorDocument 403 default
ErrorDocument 404 default
ErrorDocument 500 default

Options -Indexes

<Files how-it-works>
ForceType text/html
</Files>
<Files demo>
ForceType text/html
</Files>
<Files email>
ForceType text/html
</Files>
EOF
if $require_password; then
    cp .htpasswd dist/
fi

mkdir dist/doc/
cp -p ../doc/*.{gif,png,svg} dist/doc/

rsync -avP --delete-after dist/ \
    "${USER}@${DOMAIN}:${DOMAIN}/"
